#!/bin/bash
# ============================================================
#  Metal Arm CAN Setup Script
#  Auto-detect USB-CAN adapters by SERIAL number,
#  generate udev rules, bring up SocketCAN interfaces.
#
#  Adapter→interface mapping is per-machine and stored in `can_map.conf`
#  (generated by `setup`). Roles: can0 = slave/follower, can1 = master/leader.
#
#  FIRST TIME ON A NEW MACHINE / NEW ADAPTERS:
#    ./start_can.sh setup        teach which physical adapter is which (one-time)
#
#  Usage:
#    ./start_can.sh              start all interfaces (auto-detect & refresh)
#    ./start_can.sh setup        teach adapter→role map, save to can_map.conf
#    ./start_can.sh status       show current status
#    ./start_can.sh stop         stop all interfaces
# ============================================================

set -uo pipefail

# ─── Configuration ─────────────────────────────────────────
# Interface name → (role, serial)
#   serial: full USB serial string — locks this physical adapter to this interface.
#
# These are only DEFAULTS. Per-machine serials live in `can_map.conf` (created by
# `./start_can.sh setup`) and OVERRIDE the values below, so a new user never edits
# this script — they just run setup once on their own adapters.
declare -A CAN_IFACE=(
    ["can0"]="slave|003000274746570E20313333"
    ["can1"]="master|204835863130"
)

# Role assignment order used by `setup` (keeps master/slave deterministic instead
# of depending on USB enumeration order). Edit only if you add more arms.
SETUP_ORDER=("can0" "can1")

# slcand parameters
SLCAND_OPTS="-o -f -s8"
TXQUEUELEN=1000

# Known USB-CAN adapter vendor/product pairs
CAN_ADAPTERS=("ad50:60c4" "16d0:117e")

# File paths
UDEV_RULES_FILE="/etc/udev/rules.d/99-makermods-metal-can.rules"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Sudo password (empty = interactive prompt, the portable default).
# A user who wants unattended sudo can set SUDO_PASS in can_map.conf instead of
# editing this shared script.
SUDO_PASS=""

# Per-machine config: serial→interface map and optional SUDO_PASS. Generated by
# `./start_can.sh setup`. Sourced here so it overrides the defaults above. Keep it
# out of version control — it is specific to this machine's physical adapters.
CONFIG_FILE="${SCRIPT_DIR}/can_map.conf"
# shellcheck source=/dev/null
[ -f "$CONFIG_FILE" ] && source "$CONFIG_FILE"

# ─── Helpers ───────────────────────────────────────────────
GREEN=$(tput setaf 2 2>/dev/null || true)
YELLOW=$(tput setaf 3 2>/dev/null || true)
RED=$(tput setaf 1 2>/dev/null || true)
RESET=$(tput sgr0 2>/dev/null || true)

log()  { echo -e "${GREEN}[+]${RESET} $*"; }
warn() { echo -e "${YELLOW}[!]${RESET} $*"; }
err()  { echo -e "${RED}[X]${RESET} $*" >&2; }

_sudo() {
    # Run command via sudo. Uses SUDO_PASS if set, otherwise interactive.
    if [ "$(id -u)" -ne 0 ]; then
        if [ -n "$SUDO_PASS" ]; then
            echo "$SUDO_PASS" | sudo -S "$@" 2>/dev/null
        else
            sudo "$@"
        fi
    else
        "$@"
    fi
}

_sudo_write() {
    # Write stdin to a file as root (avoids pipe issues with _sudo + tee)
    local target="$1"
    if [ "$(id -u)" -ne 0 ]; then
        if [ -n "$SUDO_PASS" ]; then
            echo "$SUDO_PASS" | sudo -S tee "$target" > /dev/null 2>/dev/null
        else
            sudo tee "$target" > /dev/null
        fi
    else
        tee "$target" > /dev/null
    fi
}

# ─── Adapter Detection ─────────────────────────────────────

detect_all_adapters() {
    # Returns: "DEVICE|VID|PID|SERIAL" one per line
    for dev in /dev/ttyACM*; do
        [ -e "$dev" ] || continue
        local vid pid serial
        vid=$(udevadm info -a -n "$dev" 2>/dev/null | grep -oP 'ATTRS{idVendor}=="\K[^"]+' | head -1)
        pid=$(udevadm info -a -n "$dev" 2>/dev/null | grep -oP 'ATTRS{idProduct}=="\K[^"]+' | head -1)
        serial=$(udevadm info -a -n "$dev" 2>/dev/null | grep -oP 'ATTRS{serial}=="\K[^"]+' | head -1)

        for pair in "${CAN_ADAPTERS[@]}"; do
            IFS=':' read -r v p <<< "$pair"
            if [ "$vid" = "$v" ] && [ "$pid" = "$p" ]; then
                echo "$dev|$vid|$pid|$serial"
                break
            fi
        done
    done
}

find_device_by_serial() {
    local target_serial="$1"
    while IFS='|' read -r dev vid pid serial; do
        if [ "$serial" = "$target_serial" ]; then
            echo "$dev"
            return 0
        fi
    done < <(detect_all_adapters)
    return 1
}

# ─── Udev Rules ────────────────────────────────────────────

refresh_udev_rules() {
    # Regenerate udev rules for all currently plugged adapters.
    # Called on every 'start' to keep rules in sync with hardware.
    local count=0
    local rules=""

    while IFS='|' read -r dev vid pid serial; do
        local target_iface=""
        for iface in "${!CAN_IFACE[@]}"; do
            IFS='|' read -r role cfg_serial <<< "${CAN_IFACE[$iface]}"
            if [ "$serial" = "$cfg_serial" ]; then
                target_iface="$iface"
                break
            fi
        done

        if [ -n "$target_iface" ]; then
            local symlink="makermods_metal_${target_iface}"
            rules+="SUBSYSTEM==\"tty\", ATTRS{idVendor}==\"${vid}\", ATTRS{idProduct}==\"${pid}\", ATTRS{serial}==\"${serial}\", SYMLINK+=\"${symlink}\"
"
            IFS='|' read -r role _ <<< "${CAN_IFACE[$target_iface]}"
            log "  Udev: /dev/${symlink} ← ${dev}  (${vid}:${pid}, ${role})"
            ((count++))
        fi
    done < <(detect_all_adapters || true)

    if [ "$count" -eq 0 ]; then
        warn "No known adapters detected — skipping udev rules update"
        return 0
    fi

    # Write rules file (overwrites old, removes stale entries)
    echo "$rules" | _sudo_write "$UDEV_RULES_FILE" || true
    _sudo chmod 644 "$UDEV_RULES_FILE" || true

    # Remove any old rules from previous script versions
    _sudo rm -f /etc/udev/rules.d/makermods_metal_can.rules 2>/dev/null || true

    # Reload and trigger
    _sudo udevadm control --reload-rules 2>/dev/null || true
    _sudo udevadm trigger 2>/dev/null || true
    sleep 1

    # Report symlinks
    for iface in "${!CAN_IFACE[@]}"; do
        local link="/dev/makermods_metal_${iface}"
        IFS='|' read -r role cfg_serial <<< "${CAN_IFACE[$iface]}"
        local real_dev
        real_dev=$(find_device_by_serial "$cfg_serial" 2>/dev/null || true)
        if [ -n "$real_dev" ]; then
            if [ -L "$link" ]; then
                log "  ${link} → $(readlink -f "$link")" || true
            else
                warn "  ${link} not created (udev trigger may need manual run):"
                warn "     sudo udevadm trigger"
            fi
        fi
    done
}

# ─── Interface Control ─────────────────────────────────────

start_interface() {
    local iface="$1"
    local device="$2"
    local role="$3"

    [ -e "$device" ] || { err "Device $device not found"; return 1; }

    # Kill any stale slcand on this interface
    if pgrep -f "slcand.*${iface}" > /dev/null 2>&1; then
        _sudo pkill -f "slcand.*${iface}" 2>/dev/null || true
        sleep 0.5
    fi

    _sudo slcand $SLCAND_OPTS "$device" "$iface"
    sleep 1
    _sudo ip link set "$iface" up 2>/dev/null || _sudo ifconfig "$iface" up 2>/dev/null || true
    _sudo ip link set "$iface" txqueuelen "$TXQUEUELEN"

    if ip link show "$iface" 2>/dev/null | grep -q "UP"; then
        log "  ${iface} → UP  (${role})"
        return 0
    else
        err "  ${iface} failed to start"
        return 1
    fi
}

stop_interface() {
    local iface="$1"
    _sudo ip link set "$iface" down 2>/dev/null || _sudo ifconfig "$iface" down 2>/dev/null || true
    if pgrep -f "slcand.*${iface}" > /dev/null 2>&1; then
        _sudo pkill -f "slcand.*${iface}" 2>/dev/null || true
    fi
}

cleanup_stale() {
    # Kill any slcand processes not associated with our configured interfaces
    while read -r pid cmdline; do
        local found=0
        for iface in "${!CAN_IFACE[@]}"; do
            if echo "$cmdline" | grep -q "$iface"; then
                found=1
                break
            fi
        done
        if [ "$found" -eq 0 ]; then
            warn "Killing stale slcand (pid=$pid): $cmdline"
            _sudo kill "$pid" 2>/dev/null || true
        fi
    done < <(pgrep -af slcand 2>/dev/null || true)

    # Bring down any CAN interfaces not in our config
    for iface_path in /sys/class/net/can*; do
        [ -e "$iface_path" ] || continue
        local name
        name=$(basename "$iface_path")
        if [ -z "${CAN_IFACE[$name]+x}" ]; then
            warn "Tearing down unknown CAN interface: $name"
            _sudo ip link set "$name" down 2>/dev/null || true
        fi
    done
}

# ─── Status Display ────────────────────────────────────────

show_status() {
    echo "══════════════════════════════════════════════════════"
    echo "  Metal Arm CAN Status"
    echo "══════════════════════════════════════════════════════"

    echo ""
    echo "USB-CAN adapters detected:"
    while IFS='|' read -r dev vid pid serial; do
        printf "  %-14s  %s:%-5s  serial=%-26s" "$dev" "$vid" "$pid" "$serial"
        for iface in "${!CAN_IFACE[@]}"; do
            IFS='|' read -r role cfg_serial <<< "${CAN_IFACE[$iface]}"
            if [ "$serial" = "$cfg_serial" ]; then
                printf " → %s (%s)" "$iface" "$role"
            fi
        done
        echo ""
    done < <(detect_all_adapters)
    if [ -z "$(detect_all_adapters)" ]; then
        echo "  (none)"
    fi

    echo ""
    printf "%-8s %-8s %-12s %-8s %s\n" "IFACE" "ROLE" "STATE" "slcand" "DEVICE"
    echo "──────────────────────────────────────────────────────────"

    for iface in "${!CAN_IFACE[@]}"; do
        IFS='|' read -r role serial <<< "${CAN_IFACE[$iface]}"

        local state="N/A" st_color="$RED"
        if ip link show "$iface" 2>/dev/null | grep -q "UP"; then
            state="UP"; st_color="$GREEN"
        elif ip link show "$iface" 2>/dev/null | grep -q "DOWN"; then
            state="DOWN"; st_color="$YELLOW"
        fi

        local slcand_mark="✗"
        pgrep -f "slcand.*${iface}" > /dev/null 2>&1 && slcand_mark="✓"

        local dev_display
        if [ -L "/dev/makermods_metal_${iface}" ]; then
            dev_display="/dev/makermods_metal_${iface} → $(readlink -f "/dev/makermods_metal_${iface}")"
        else
            local real_dev
            real_dev=$(find_device_by_serial "$serial" 2>/dev/null || true)
            if [ -n "$real_dev" ]; then
                dev_display="${real_dev}"
            else
                dev_display="${RED}(not plugged)${RESET}"
            fi
        fi

        printf "${st_color}%-8s${RESET} %-8s %s%-12s${RESET} %-8s %s\n" \
            "$iface" "$role" "$st_color" "$state" "$slcand_mark" "$dev_display"
    done

    echo ""
    echo "Commands:"
    echo "  ./start_can.sh          start all + refresh udev rules"
    echo "  ./start_can.sh setup    teach adapter→role map (run once per machine)"
    echo "  ./start_can.sh stop     stop all"
    echo "  ./start_can.sh status   this view"
}

# ─── Persist mapping ───────────────────────────────────────
save_config() {
    # Write the current serial→interface map to can_map.conf so it survives across
    # runs. Without this, a re-detect would be lost on the next invocation.
    {
        echo "# makermods CAN per-machine mapping — generated by './start_can.sh setup'."
        echo "# Maps each physical USB-CAN adapter (by USB serial) to a CAN interface."
        echo "# Machine-specific; do NOT commit. Re-run setup if you swap adapters."
        for iface in "${!CAN_IFACE[@]}"; do
            echo "CAN_IFACE[\"${iface}\"]=\"${CAN_IFACE[$iface]}\""
        done
    } > "$CONFIG_FILE"
    log "Saved mapping → $CONFIG_FILE"
}

# ─── Main ──────────────────────────────────────────────────

ACTION="${1:-start}"

case "$ACTION" in
    setup|reset)
        # Interactive teach: map each role by plugging that adapter in ALONE.
        # This is the only portable way to bind two identical adapters to fixed
        # roles — USB enumeration order is not stable, so we ask the human.
        echo "══════════════════════════════════════════════════════"
        echo "  Metal Arm CAN — Setup (teach adapter mapping)"
        echo "══════════════════════════════════════════════════════"
        log "You'll plug in each arm's adapter one at a time."

        # Stop everything first so detection is clean.
        for iface in "${!CAN_IFACE[@]}"; do
            stop_interface "$iface" 2>/dev/null || true
        done

        for iface in "${SETUP_ORDER[@]}"; do
            IFS='|' read -r role _ <<< "${CAN_IFACE[$iface]}"
            echo ""
            read -rp ">>> Plug in ONLY the '${role}' arm adapter (→ ${iface}); unplug the other. Press Enter..."
            mapfile -t found < <(detect_all_adapters)
            if [ "${#found[@]}" -eq 0 ]; then
                err "No USB-CAN adapter detected. Check the cable/power and retry."
                exit 1
            fi
            if [ "${#found[@]}" -gt 1 ]; then
                warn "Detected ${#found[@]} adapters; using the first. For a reliable map, plug in only one."
            fi
            IFS='|' read -r dev vid pid serial <<< "${found[0]}"
            if [ -z "$serial" ]; then
                err "Adapter on ${dev} reports no USB serial; cannot map it reliably."
                exit 1
            fi
            CAN_IFACE[$iface]="${role}|${serial}"
            log "  ${iface} (${role}) ← ${dev}  serial=${serial}  (${vid}:${pid})"
        done

        echo ""
        save_config
        refresh_udev_rules
        echo ""
        log "Setup complete. Plug in BOTH adapters, then run './start_can.sh'."
        ;;

    start)
        echo "══════════════════════════════════════════════════════"
        echo "  Metal Arm CAN — Starting"
        echo "══════════════════════════════════════════════════════"

        # 1. Kill stale slcand processes & unknown interfaces
        echo ""
        log "Cleaning up stale interfaces..."
        cleanup_stale

        # 2. Refresh udev rules from current hardware state
        echo ""
        log "Refreshing udev rules..."
        refresh_udev_rules

        # 3. Start configured interfaces
        echo ""
        any_up=0
        for iface in "${!CAN_IFACE[@]}"; do
            IFS='|' read -r role serial <<< "${CAN_IFACE[$iface]}"

            if [ "$serial" = "auto" ] || [ -z "$serial" ]; then
                warn "Skipping ${iface} (${role}): serial not configured — run './start_can.sh reset'"
                continue
            fi

            device=$(find_device_by_serial "$serial" 2>/dev/null || true)

            if [ -z "$device" ]; then
                warn "Skipping ${iface} (${role}): adapter serial=${serial} not plugged"
                continue
            fi

            log "Starting ${iface} (${role}) via ${device}..."
            start_interface "$iface" "$device" "$role" && any_up=1
        done

        if [ "$any_up" -eq 0 ]; then
            warn "No interfaces started. Are the adapters plugged in?"
            warn "Run './start_can.sh reset' to re-detect."
        fi

        echo ""
        show_status
        ;;

    stop)
        echo "Stopping all CAN interfaces..."
        for iface in "${!CAN_IFACE[@]}"; do
            IFS='|' read -r role _ <<< "${CAN_IFACE[$iface]}"
            log "Stopping ${iface} (${role})..."
            stop_interface "$iface"
        done
        cleanup_stale
        log "All interfaces stopped."
        ;;

    status)
        show_status
        ;;

    *)
        echo "Usage: $0 {start|setup|stop|status}"
        exit 1
        ;;
esac
